import React from 'react';

const Home = () => (
  <section>
    <p>Home ... Lorem ipsum dolor sit amet, consectetur adipisicing elit. Necessitatibus, sit.</p>
    <img src='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAHQAAAB0CAYAAABUmhYnAAAAAklEQVR4AewaftIAAAKeSURBVO3BQY7cQAwEwUxC//9yeY88NSBIM/bSjDA/WGMUa5RijVKsUYo1SrFGKdYoxRqlWKMUa5RijVKsUYo1SrFGKdYoxRrl4iGVb0rCicoTSehUvikJTxRrlGKNUqxRLl6WhDep3JGETuUkCXck4U0qbyrWKMUapVijXHyYyh1JuEPlJAmdSqfSJeEOlTuS8EnFGqVYoxRrlIvhVLokdCqTFGuUYo1SrFEuhklCp/I/KdYoxRqlWKNcfFgSJkvCv6RYoxRrlGKNcvEylclU/mXFGqVYoxRrlIuHkjBZEn6TYo1SrFGKNcrFQypdEjqVNyWhS8JJEp5QeVMSPqlYoxRrlGKNcvFQEjqVO5LQqXRJeEKlS8KJSpeETuUkCZ3KNxVrlGKNUqxRLj4sCScqXRI6lS4JncpJEp5Q6ZLQqXQqXRI6lZMkPFGsUYo1SrFGuXhZEk5U7kjCSRI6lU6lS8JJEjqV36RYoxRrlGKNcvEylZMkdCqdykkSOpU7VO5IwhMq31SsUYo1SrFGMT/4xVS6JJyo3JGEO1TuSMKbijVKsUYp1igXD6l8UxK6JHQqf1MS7lDpkvBEsUYp1ijFGuXiZUl4k8qJykkSTlROVE6S0KnckYQ3FWuUYo1SrFEuPkzljiS8SeWOJJyodCpdEjqVLgmdSpeEJ4o1SrFGKdYoF8MkoVM5SUKn0iWhS0Kn0qnckYQ3FWuUYo1SrFEuhlHpktCpdConKnckoVP5pmKNUqxRijXKxYcl4ZOS8EQSTlS6JJyodEk4UemS8ESxRinWKMUa5eJlKt+k0iWhU7lDpUtCp/KmJLypWKMUa5RijWJ+sMYo1ijFGqVYoxRrlGKNUqxRijVKsUYp1ijFGqVYoxRrlGKNUqxRijXKHyvg7gWCju0yAAAAAElFTkSuQmCC' />
  </section>
);

export default Home;
